/**
 * Pure helper functions for the daily-summaries cron route.
 *
 * Extracted so they can be unit-tested independently of Supabase.
 */

import { formatCurrency, formatDate } from "@/lib/format"

// ============================================================================
// Types
// ============================================================================

export interface DailySummaryData {
  ownerName: string
  businessName: string | null
  date: Date
  paymentsReceived: {
    count: number
    total: number
    breakdown: { method: string; amount: number }[]
  }
  expensesRecorded: {
    count: number
    total: number
    breakdown: { category: string; amount: number }[]
  }
  newTenants: number
  exits: number
  pendingDues: {
    total: number
    count: number
  }
  occupancyRate: number
  openComplaints: number
}

// ============================================================================
// generateWhatsAppSummary
// ============================================================================

/**
 * Builds a WhatsApp-friendly daily summary message from aggregated data.
 * Pure function — no DB calls, no side effects.
 */
export function generateWhatsAppSummary(data: DailySummaryData): string {
  const lines: string[] = []
  const dateStr = formatDate(data.date)
  const bizName = data.businessName || data.ownerName

  lines.push(`📊 *Daily Summary - ${bizName}*`)
  lines.push(`📅 ${dateStr}`)
  lines.push("")

  if (data.paymentsReceived.count > 0) {
    lines.push(`💰 *Payments Received*`)
    lines.push(`   ${data.paymentsReceived.count} payments = ${formatCurrency(data.paymentsReceived.total)}`)
    for (const { method, amount } of data.paymentsReceived.breakdown) {
      lines.push(`   • ${method}: ${formatCurrency(amount)}`)
    }
    lines.push("")
  } else {
    lines.push(`💰 No payments received`)
    lines.push("")
  }

  if (data.expensesRecorded.count > 0) {
    lines.push(`📉 *Expenses*`)
    lines.push(`   ${data.expensesRecorded.count} expenses = ${formatCurrency(data.expensesRecorded.total)}`)
    for (const { category, amount } of data.expensesRecorded.breakdown.slice(0, 3)) {
      lines.push(`   • ${category}: ${formatCurrency(amount)}`)
    }
    lines.push("")
  }

  const net = data.paymentsReceived.total - data.expensesRecorded.total
  lines.push(`📈 *Net*: ${net >= 0 ? "+" : ""}${formatCurrency(net)}`)
  lines.push("")

  lines.push(`🏠 Occupancy: ${data.occupancyRate.toFixed(0)}%`)
  if (data.pendingDues.total > 0) {
    lines.push(`⏰ Pending: ${formatCurrency(data.pendingDues.total)} (${data.pendingDues.count} bills)`)
  }
  if (data.openComplaints > 0) {
    lines.push(`⚠️ Complaints: ${data.openComplaints} open`)
  }

  if (data.newTenants > 0 || data.exits > 0) {
    lines.push("")
    if (data.newTenants > 0) lines.push(`👥 +${data.newTenants} new tenant${data.newTenants > 1 ? "s" : ""}`)
    if (data.exits > 0) lines.push(`👋 -${data.exits} exit${data.exits > 1 ? "s" : ""}`)
  }

  lines.push("")
  lines.push(`_Generated by ManageKar_`)

  return lines.join("\n")
}
