/**
 * Status Configuration Module
 *
 * Re-exports all status configs from their respective modules.
 * Import from "@/lib/status" or "@/lib/status-config" (backward compat).
 */

// Types
export type { StatusDotVariant, StatusVariant, StatusConfig, StatusConfigWithIcon } from "./shared"

// Shared
export { ACTIVE_STATUS, VISITOR_STATUS, getStatusConfig, getStatusInfo } from "./shared"
export { INQUIRY_STATUS_LABELS, INQUIRY_SOURCE_LABELS, INQUIRY_STATUS_COLORS, INQUIRY_SOURCE_COLORS } from "./shared"
export { OCCUPANCY_STATUS_COLORS, PG_ROOM_STATUS_COLORS } from "./shared"
export { MATCH_TYPE_LABELS, MATCH_TYPE_COLORS } from "./shared"
export { AUDIT_ACTION_LABELS, AUDIT_ACTION_COLORS, AUDIT_ACTION_ICONS } from "./shared"
export { NOTIFICATION_TYPE_STYLES } from "./shared"

// Tenant & Approval
export { TENANT_STATUS, APPROVAL_STATUS, APPROVAL_TYPE_LABELS, APPROVAL_PRIORITY } from "./tenant"

// Complaint
export { COMPLAINT_STATUS, COMPLAINT_PRIORITY, COMPLAINT_CATEGORIES } from "./complaint"

// Billing & Related
export {
  REFUND_STATUS, EXIT_CLEARANCE_STATUS, PAYMENT_METHODS,
  DOCUMENT_STATUS, POLICE_VERIFICATION_STATUS,
  REFUND_TYPE_LABELS, REFUND_STATUS_LABELS,
  NOTICE_TYPES, NOTICE_AUDIENCES, NOTICE_TYPE_LABELS,
  NOTICE_TYPE_CONFIG, NOTICE_TYPE_DISPLAY_CONFIG, METER_READING_TYPE_CONFIG,
  METER_TYPES, METER_STATUS_LABELS, METER_TYPE_LABELS,
  PERSON_TAG_COLORS, PERSON_TAG_ICONS,
  KITCHEN_WASTAGE_REASON_LABELS, BILL_PAYMENT_STATUS_LABELS,
  BILL_STATUS, BILL_STATUS_TEXT_COLORS, ROOM_STATUS,
  labelsToOptions,
  PAYMENT_METHOD_OPTIONS, REFUND_PAYMENT_MODE_OPTIONS, REFUND_TYPE_OPTIONS,
  EXPENSE_PAYMENT_MODE_OPTIONS, EXPENSE_DAILY_SPEND_PAYMENT_MODE_OPTIONS,
  EXPENSE_MISC_PAYMENT_MODE_OPTIONS,
  PAYMENT_STATUS_OPTIONS, EXPENSE_BILL_STATUS_OPTIONS, UNIT_OPTIONS,
  POLICE_VERIFICATION_STATUS_OPTIONS,
  NOTICE_TYPE_OPTIONS, NOTICE_AUDIENCE_OPTIONS,
  METER_STATUS_OPTIONS, METER_TYPE_OPTIONS,
  BOOLEAN_STRING_OPTIONS,
} from "./billing"

// Visitors
export { VISITOR_TYPE_COLORS, VISITOR_TYPE_ICONS } from "./visitors"

// Library
export {
  LIBRARY_SEAT_STATUS_LABELS, LIBRARY_MEMBER_STATUS_LABELS,
  LIBRARY_MEMBERSHIP_STATUS_LABELS, LIBRARY_LOCKER_STATUS_LABELS,
  LIBRARY_LOCKER_SIZE_LABELS, LIBRARY_WAITLIST_STATUS_LABELS,
  LIBRARY_PAYMENT_TYPE_LABELS, LIBRARY_PAYMENT_STATUS_LABELS,
  LIBRARY_PAYMENT_METHOD_LABELS,
  LIBRARY_MEMBER_STATUS_CONFIG, LIBRARY_SEAT_STATUS_CONFIG,
  LIBRARY_LOCKER_STATUS_CONFIG, LIBRARY_LOCKER_SIZE_CONFIG,
  LIBRARY_MEMBERSHIP_STATUS_CONFIG, LIBRARY_PAYMENT_TYPE_CONFIG,
  LIBRARY_PAYMENT_METHOD_CONFIG, LIBRARY_PAYMENT_STATUS_CONFIG,
  LIBRARY_WAITLIST_STATUS_CONFIG,
  LIBRARY_PAYMENT_METHOD_OPTIONS, LIBRARY_PAYMENT_METHOD_FULL_OPTIONS,
  LIBRARY_PAYMENT_TYPE_OPTIONS, LIBRARY_PAYMENT_STATUS_OPTIONS,
  LIBRARY_MEMBER_STATUS_OPTIONS, LIBRARY_WAITLIST_STATUS_OPTIONS,
} from "./library"
